### ISSUE TITLE
node your_script.js --node-env=production does not work

### ISSUE THREAD

**Issue by neuronflow** [kerimdzhanov/dotenv-flow#26] opened 2020-02-10 00:44 UTC
`$ node your_script.js --node-env=production`
does not work, but:
`$ NODE_ENV=production node your_script.js`
does

Ubuntu1804
node 13.7.0
`

**Comment by kerimdzhanov** [comment] 2020-02-10 12:58
Possibly duplicate of #25

**Closed** 2020-02-27 12:48 UTC
